// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxasxlkrjxctrhwrmvlu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4YXN4bGtyanhjdHJod3Jtdmx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM3NzY1NDgsImV4cCI6MjA0OTM1MjU0OH0.PL-tqz7ddCdudgtMfBGjsEaftdAjlc9fG_T-sQC2c7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);